#ifndef ONIONHEN_DAEMON_ELF
#define ONIONHEN_DAEMON_ELF "../../bin/daemon.elf"
#endif
#ifndef ONIONHEN_UTIL_ELF
#define ONIONHEN_UTIL_ELF "../../bin/util.elf"
#endif
#ifndef ONIONHEN_ELFLDR_ELF
#define ONIONHEN_ELFLDR_ELF "../../bin/onion_elfldr.elf"
#endif
#ifndef ONIONHEN_KSTUFF_ELF
#define ONIONHEN_KSTUFF_ELF "../assets/kstuff.elf"
#endif
#ifndef ONIONHEN_ICON_ASSET_DIR
#define ONIONHEN_ICON_ASSET_DIR "../assets"
#endif

__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"" ONIONHEN_DAEMON_ELF "\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"" ONIONHEN_UTIL_ELF "\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global onion_elfldr_start\n"
        ".type   onion_elfldr_start, @object\n"
        ".align  16\n"
        "onion_elfldr_start:\n"
        ".incbin \"" ONIONHEN_ELFLDR_ELF "\"\n"
        "onion_elfldr_end:\n"
        ".global onion_elfldr_size\n"
        ".type   onion_elfldr_size, @object\n"
        ".align  4\n"
        "onion_elfldr_size:\n"
        ".int    onion_elfldr_end - onion_elfldr_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"../assets/onionhen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"

        /* Toolbox menu icons → /data/OnionHEN/assets/ (XML uses //user//data//...)
         * One block per icon, generated by CMake from the icon list. */
#include "icon_assets.inc"

    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"" ONIONHEN_KSTUFF_ELF "\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"
);
